### ISSUE TITLE
Select "Assignment Overall Score" when we insert grading into editor

### ISSUE THREAD

**Issue by tsungtingdu** [tsungtingdu/ac-ta-tool-helper#24]
## background

Now we are able to insert grading and tag student automatically with our button, but we still need to select "Assignment Overall Score" after reviewing a assignments.

Since the "Assignment Overall Score" is always related to the grading that we inserted, we could select "Assignment Overall Score" when we insert grading into editor at the same time.

**Comment by TomatoSoup0126** [comment]
類似期末考的作業會有複數批改成績，最後的總成績會需要按照前面的值來決定？
Q1: Try harder
Q2: Excellent
Q3: Excellent
總成績: Try harder

**Comment by tsungtingdu** [comment]
好問題，實際上大家是怎麼做的啊 XD

不過我想這裡可以不用有一個標準答案，我們可以先幫助教 pre-select，之後助教再看情況調整最後的值。我們這裡只要有一個固定的計算方式就行 (e.g., 權重分配)
