### ISSUE TITLE
新增 Exceed expectations 按鈕

### ISSUE THREAD

**Issue by tsungtingdu** [tsungtingdu/ac-ta-tool-helper#9]
## background

批改作業的時候有三個等第，目前 extension 只有呈現 `Try harder` 和 `Meet expectations` buttons，尚未放入 `Exceed expectations` button 

## design 

由於放入 `Exceed expectations` button 會造成破版，需要思考不同的呈現方式，譬如
- 使用 drop-down list
- 減少 button 內部的文字，舉例 `Try Harder` 縮寫成 `T`，然後改用 tooltip 呈現全文

歡迎其他不同的 idea

**Comment by TomatoSoup0126** [comment]
目前批改等地共五種
- Try harder 
- Meet expectations
- Exceed expectations
- Good 
- Excellent

五個按鈕勢必無法擠在目前的同一行上，可能做成兩行？
若採用縮寫會變成T / M / E 這樣嗎？

另外在想需不需要把標記學生獨立做成一顆按鈕？ 之後在QA頁面就可以單純標記學生，不過QA頁面可能有複數的學生在同一討論串登場，要標記指定的學生會更複雜點。

**Comment by tsungtingdu** [comment]
random idea: chrome extension 有辦法吃特定「快捷鍵組合」嗎？

**Comment by TomatoSoup0126** [comment]
https://developer.chrome.com/docs/extensions/reference/commands/
好像可以耶

**Comment by tsungtingdu** [comment]
let's use dropdown
